### PR TITLE
Fix missing volume name and re-implement adding drivetype to filesystem plugin

### LINKED ISSUE #1418: Windows drives volume name always empty
## Description

The volume name always appears empty in windows filesystems.

## Ohai Version

15.7.2

## Platform Version

Windows 8.1 (64-bit).

## Ohai Output

```
{
  "C:": {
    "kb_size": 104849207,
    "kb_available": 15270641,
    "kb_used": 89578566,
    "percent_used": 85,
    "fs_type": "ntfs",
    "volume_name": ""
  }
}
```

## Expected Output

My C: drive has a volume name ("Windows8_OS"), so that should show up in the volume_name instead of it being blank.

### PR DESCRIPTION
**Pull request by sshock**
Fix volume name and add drive type to filesystem plugin (windows-specific).

## Description
1. Fix the volume name, which previously was always empty due to a misnamed field in Win32_LogicalDisk.

2. Re-implement PR #1403 to add drive type.  That PR had conflicts due to PR #1267.  This PR fixes that and includes a few more specs.

## Related Issue
Fixes #1418.  Replaces #1403.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:
- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

## Filesystem Comparison:

Before:

```
  "filesystem": {
    "C:": {
      "kb_size": 104849207,
      "kb_available": 15268880,
      "kb_used": 89580327,
      "percent_used": 85,
      "fs_type": "ntfs",
      "volume_name": ""
    }
  },
```

After:

```
  "filesystem": {
    "C:": {
      "kb_size": 104849207,
      "kb_available": 16072687,
      "kb_used": 88776520,
      "percent_used": 84,
      "fs_type": "ntfs",
      "drive_type": 3,
      "drive_type_string": "local",
      "drive_type_human": "Local Fixed Disk",
      "volume_name": "Windows8_OS"
    }
```

## Filesystem2 Comparison:

Before:

```
  "filesystem2": {
    "by_device": {
      "": {
        "kb_size": 104849207,
        "kb_available": 15268880,
        "kb_used": 89580327,
        "percent_used": 85,
        "fs_type": "ntfs",
        "volume_name": "",
        "mounts": [
          "C:"
        ]
      }
    },
    "by_mountpoint": {
      "C:": {
        "kb_size": 104849207,
        "kb_available": 15268880,
        "kb_used": 89580327,
        "percent_used": 85,
        "fs_type": "ntfs",
        "volume_name": "",
        "devices": [
          ""
        ]
      }
    },
    "by_pair": {
      ",C:": {
        "kb_size": 104849207,
        "kb_available": 15268880,
        "kb_used": 89580327,
        "percent_used": 85,
        "mount": "C:",
        "fs_type": "ntfs",
        "volume_name": "",
        "device": ""
      }
    }
  },
```

After:

```
  "filesystem2": {
    "by_device": {
      "windows8_os": {
        "kb_size": 104849207,
        "kb_available": 16072687,
        "kb_used": 88776520,
        "percent_used": 84,
        "fs_type": "ntfs",
        "drive_type": 3,
        "drive_type_string": "local",
        "drive_type_human": "Local Fixed Disk",
        "volume_name": "Windows8_OS",
        "mounts": [
          "C:"
        ]
      }
    },
    "by_mountpoint": {
      "C:": {
        "kb_size": 104849207,
        "kb_available": 16072687,
        "kb_used": 88776520,
        "percent_used": 84,
        "fs_type": "ntfs",
        "drive_type": 3,
        "drive_type_string": "local",
        "drive_type_human": "Local Fixed Disk",
        "volume_name": "Windows8_OS",
        "devices": [
          "windows8_os"
        ]
      }
    },
    "by_pair": {
      "windows8_os,C:": {
        "kb_size": 104849207,
        "kb_available": 16072687,
        "kb_used": 88776520,
        "percent_used": 84,
        "mount": "C:",
        "fs_type": "ntfs",
        "drive_type": 3,
        "drive_type_string": "local",
        "drive_type_human": "Local Fixed Disk",
        "volume_name": "Windows8_OS",
        "device": "windows8_os"
      }
    }
  },
```

### CODE REVIEW

File: spec/unit/plugins/windows/filesystem_spec.rb [hunk 1]
```diff
@@ -104,6 +111,9 @@
 
         {
           "fs_type" => "fat32",
+          "drive_type" => 2,
+          "drive_type_string" => "removable",
```
Comment (tas50) [inline spec/unit/plugins/windows/filesystem_spec.rb]: Thanks for adding the string value as well

**Comment by tas50** [comment]
Thanks @sshock !
